// D1 Schema - Central Database
export * from "./games";
export * from "./characters";
export * from "./npcs";
export * from "./assets";

// Note: Better Auth tables (users, sessions, accounts, verificationTokens)
// are auto-generated by the Drizzle adapter when auth is initialized.
