/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as BuyCreditsRouteImport } from './routes/buy-credits'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GamesNewRouteImport } from './routes/games/new'
import { Route as GamesMineRouteImport } from './routes/games/mine'
import { Route as BuyCreditsSuccessRouteImport } from './routes/buy-credits/success'
import { Route as AuthLinkRouteImport } from './routes/auth/link'
import { Route as GamesIdIndexRouteImport } from './routes/games/$id/index'
import { Route as GamesIdEditRouteImport } from './routes/games/$id/edit'
import { Route as GamesIdPlayIndexRouteImport } from './routes/games/$id/play/index'
import { Route as GamesIdPlayNewRouteImport } from './routes/games/$id/play/new'
import { Route as GamesIdPlaySessionIdRouteImport } from './routes/games/$id/play/$sessionId'
import { Route as GamesIdPlaySessionIdSettingsRouteImport } from './routes/games/$id/play/$sessionId/settings'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyCreditsRoute = BuyCreditsRouteImport.update({
  id: '/buy-credits',
  path: '/buy-credits',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesNewRoute = GamesNewRouteImport.update({
  id: '/games/new',
  path: '/games/new',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesMineRoute = GamesMineRouteImport.update({
  id: '/games/mine',
  path: '/games/mine',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyCreditsSuccessRoute = BuyCreditsSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => BuyCreditsRoute,
} as any)
const AuthLinkRoute = AuthLinkRouteImport.update({
  id: '/auth/link',
  path: '/auth/link',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesIdIndexRoute = GamesIdIndexRouteImport.update({
  id: '/games/$id/',
  path: '/games/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesIdEditRoute = GamesIdEditRouteImport.update({
  id: '/games/$id/edit',
  path: '/games/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesIdPlayIndexRoute = GamesIdPlayIndexRouteImport.update({
  id: '/games/$id/play/',
  path: '/games/$id/play/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesIdPlayNewRoute = GamesIdPlayNewRouteImport.update({
  id: '/games/$id/play/new',
  path: '/games/$id/play/new',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesIdPlaySessionIdRoute = GamesIdPlaySessionIdRouteImport.update({
  id: '/games/$id/play/$sessionId',
  path: '/games/$id/play/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesIdPlaySessionIdSettingsRoute =
  GamesIdPlaySessionIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => GamesIdPlaySessionIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/buy-credits': typeof BuyCreditsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/auth/link': typeof AuthLinkRoute
  '/buy-credits/success': typeof BuyCreditsSuccessRoute
  '/games/mine': typeof GamesMineRoute
  '/games/new': typeof GamesNewRoute
  '/games/$id/edit': typeof GamesIdEditRoute
  '/games/$id': typeof GamesIdIndexRoute
  '/games/$id/play/$sessionId': typeof GamesIdPlaySessionIdRouteWithChildren
  '/games/$id/play/new': typeof GamesIdPlayNewRoute
  '/games/$id/play': typeof GamesIdPlayIndexRoute
  '/games/$id/play/$sessionId/settings': typeof GamesIdPlaySessionIdSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/buy-credits': typeof BuyCreditsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/auth/link': typeof AuthLinkRoute
  '/buy-credits/success': typeof BuyCreditsSuccessRoute
  '/games/mine': typeof GamesMineRoute
  '/games/new': typeof GamesNewRoute
  '/games/$id/edit': typeof GamesIdEditRoute
  '/games/$id': typeof GamesIdIndexRoute
  '/games/$id/play/$sessionId': typeof GamesIdPlaySessionIdRouteWithChildren
  '/games/$id/play/new': typeof GamesIdPlayNewRoute
  '/games/$id/play': typeof GamesIdPlayIndexRoute
  '/games/$id/play/$sessionId/settings': typeof GamesIdPlaySessionIdSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/buy-credits': typeof BuyCreditsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/auth/link': typeof AuthLinkRoute
  '/buy-credits/success': typeof BuyCreditsSuccessRoute
  '/games/mine': typeof GamesMineRoute
  '/games/new': typeof GamesNewRoute
  '/games/$id/edit': typeof GamesIdEditRoute
  '/games/$id/': typeof GamesIdIndexRoute
  '/games/$id/play/$sessionId': typeof GamesIdPlaySessionIdRouteWithChildren
  '/games/$id/play/new': typeof GamesIdPlayNewRoute
  '/games/$id/play/': typeof GamesIdPlayIndexRoute
  '/games/$id/play/$sessionId/settings': typeof GamesIdPlaySessionIdSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/buy-credits'
    | '/settings'
    | '/auth/link'
    | '/buy-credits/success'
    | '/games/mine'
    | '/games/new'
    | '/games/$id/edit'
    | '/games/$id'
    | '/games/$id/play/$sessionId'
    | '/games/$id/play/new'
    | '/games/$id/play'
    | '/games/$id/play/$sessionId/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/buy-credits'
    | '/settings'
    | '/auth/link'
    | '/buy-credits/success'
    | '/games/mine'
    | '/games/new'
    | '/games/$id/edit'
    | '/games/$id'
    | '/games/$id/play/$sessionId'
    | '/games/$id/play/new'
    | '/games/$id/play'
    | '/games/$id/play/$sessionId/settings'
  id:
    | '__root__'
    | '/'
    | '/buy-credits'
    | '/settings'
    | '/auth/link'
    | '/buy-credits/success'
    | '/games/mine'
    | '/games/new'
    | '/games/$id/edit'
    | '/games/$id/'
    | '/games/$id/play/$sessionId'
    | '/games/$id/play/new'
    | '/games/$id/play/'
    | '/games/$id/play/$sessionId/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BuyCreditsRoute: typeof BuyCreditsRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  AuthLinkRoute: typeof AuthLinkRoute
  GamesMineRoute: typeof GamesMineRoute
  GamesNewRoute: typeof GamesNewRoute
  GamesIdEditRoute: typeof GamesIdEditRoute
  GamesIdIndexRoute: typeof GamesIdIndexRoute
  GamesIdPlaySessionIdRoute: typeof GamesIdPlaySessionIdRouteWithChildren
  GamesIdPlayNewRoute: typeof GamesIdPlayNewRoute
  GamesIdPlayIndexRoute: typeof GamesIdPlayIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buy-credits': {
      id: '/buy-credits'
      path: '/buy-credits'
      fullPath: '/buy-credits'
      preLoaderRoute: typeof BuyCreditsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/new': {
      id: '/games/new'
      path: '/games/new'
      fullPath: '/games/new'
      preLoaderRoute: typeof GamesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/mine': {
      id: '/games/mine'
      path: '/games/mine'
      fullPath: '/games/mine'
      preLoaderRoute: typeof GamesMineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buy-credits/success': {
      id: '/buy-credits/success'
      path: '/success'
      fullPath: '/buy-credits/success'
      preLoaderRoute: typeof BuyCreditsSuccessRouteImport
      parentRoute: typeof BuyCreditsRoute
    }
    '/auth/link': {
      id: '/auth/link'
      path: '/auth/link'
      fullPath: '/auth/link'
      preLoaderRoute: typeof AuthLinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/$id/': {
      id: '/games/$id/'
      path: '/games/$id'
      fullPath: '/games/$id'
      preLoaderRoute: typeof GamesIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/$id/edit': {
      id: '/games/$id/edit'
      path: '/games/$id/edit'
      fullPath: '/games/$id/edit'
      preLoaderRoute: typeof GamesIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/$id/play/': {
      id: '/games/$id/play/'
      path: '/games/$id/play'
      fullPath: '/games/$id/play'
      preLoaderRoute: typeof GamesIdPlayIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/$id/play/new': {
      id: '/games/$id/play/new'
      path: '/games/$id/play/new'
      fullPath: '/games/$id/play/new'
      preLoaderRoute: typeof GamesIdPlayNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/$id/play/$sessionId': {
      id: '/games/$id/play/$sessionId'
      path: '/games/$id/play/$sessionId'
      fullPath: '/games/$id/play/$sessionId'
      preLoaderRoute: typeof GamesIdPlaySessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/$id/play/$sessionId/settings': {
      id: '/games/$id/play/$sessionId/settings'
      path: '/settings'
      fullPath: '/games/$id/play/$sessionId/settings'
      preLoaderRoute: typeof GamesIdPlaySessionIdSettingsRouteImport
      parentRoute: typeof GamesIdPlaySessionIdRoute
    }
  }
}

interface BuyCreditsRouteChildren {
  BuyCreditsSuccessRoute: typeof BuyCreditsSuccessRoute
}

const BuyCreditsRouteChildren: BuyCreditsRouteChildren = {
  BuyCreditsSuccessRoute: BuyCreditsSuccessRoute,
}

const BuyCreditsRouteWithChildren = BuyCreditsRoute._addFileChildren(
  BuyCreditsRouteChildren,
)

interface GamesIdPlaySessionIdRouteChildren {
  GamesIdPlaySessionIdSettingsRoute: typeof GamesIdPlaySessionIdSettingsRoute
}

const GamesIdPlaySessionIdRouteChildren: GamesIdPlaySessionIdRouteChildren = {
  GamesIdPlaySessionIdSettingsRoute: GamesIdPlaySessionIdSettingsRoute,
}

const GamesIdPlaySessionIdRouteWithChildren =
  GamesIdPlaySessionIdRoute._addFileChildren(GamesIdPlaySessionIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BuyCreditsRoute: BuyCreditsRouteWithChildren,
  SettingsRoute: SettingsRoute,
  AuthLinkRoute: AuthLinkRoute,
  GamesMineRoute: GamesMineRoute,
  GamesNewRoute: GamesNewRoute,
  GamesIdEditRoute: GamesIdEditRoute,
  GamesIdIndexRoute: GamesIdIndexRoute,
  GamesIdPlaySessionIdRoute: GamesIdPlaySessionIdRouteWithChildren,
  GamesIdPlayNewRoute: GamesIdPlayNewRoute,
  GamesIdPlayIndexRoute: GamesIdPlayIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
