/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GamesNewRouteImport } from './routes/games/new'
import { Route as GamesMineRouteImport } from './routes/games/mine'
import { Route as AuthLinkRouteImport } from './routes/auth/link'
import { Route as GamesIdIndexRouteImport } from './routes/games/$id/index'
import { Route as GamesIdPlayRouteImport } from './routes/games/$id/play'
import { Route as GamesIdEditRouteImport } from './routes/games/$id/edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesNewRoute = GamesNewRouteImport.update({
  id: '/games/new',
  path: '/games/new',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesMineRoute = GamesMineRouteImport.update({
  id: '/games/mine',
  path: '/games/mine',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLinkRoute = AuthLinkRouteImport.update({
  id: '/auth/link',
  path: '/auth/link',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesIdIndexRoute = GamesIdIndexRouteImport.update({
  id: '/games/$id/',
  path: '/games/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesIdPlayRoute = GamesIdPlayRouteImport.update({
  id: '/games/$id/play',
  path: '/games/$id/play',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesIdEditRoute = GamesIdEditRouteImport.update({
  id: '/games/$id/edit',
  path: '/games/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/link': typeof AuthLinkRoute
  '/games/mine': typeof GamesMineRoute
  '/games/new': typeof GamesNewRoute
  '/games/$id/edit': typeof GamesIdEditRoute
  '/games/$id/play': typeof GamesIdPlayRoute
  '/games/$id': typeof GamesIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/link': typeof AuthLinkRoute
  '/games/mine': typeof GamesMineRoute
  '/games/new': typeof GamesNewRoute
  '/games/$id/edit': typeof GamesIdEditRoute
  '/games/$id/play': typeof GamesIdPlayRoute
  '/games/$id': typeof GamesIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth/link': typeof AuthLinkRoute
  '/games/mine': typeof GamesMineRoute
  '/games/new': typeof GamesNewRoute
  '/games/$id/edit': typeof GamesIdEditRoute
  '/games/$id/play': typeof GamesIdPlayRoute
  '/games/$id/': typeof GamesIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/link'
    | '/games/mine'
    | '/games/new'
    | '/games/$id/edit'
    | '/games/$id/play'
    | '/games/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/link'
    | '/games/mine'
    | '/games/new'
    | '/games/$id/edit'
    | '/games/$id/play'
    | '/games/$id'
  id:
    | '__root__'
    | '/'
    | '/auth/link'
    | '/games/mine'
    | '/games/new'
    | '/games/$id/edit'
    | '/games/$id/play'
    | '/games/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthLinkRoute: typeof AuthLinkRoute
  GamesMineRoute: typeof GamesMineRoute
  GamesNewRoute: typeof GamesNewRoute
  GamesIdEditRoute: typeof GamesIdEditRoute
  GamesIdPlayRoute: typeof GamesIdPlayRoute
  GamesIdIndexRoute: typeof GamesIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/new': {
      id: '/games/new'
      path: '/games/new'
      fullPath: '/games/new'
      preLoaderRoute: typeof GamesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/mine': {
      id: '/games/mine'
      path: '/games/mine'
      fullPath: '/games/mine'
      preLoaderRoute: typeof GamesMineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/link': {
      id: '/auth/link'
      path: '/auth/link'
      fullPath: '/auth/link'
      preLoaderRoute: typeof AuthLinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/$id/': {
      id: '/games/$id/'
      path: '/games/$id'
      fullPath: '/games/$id'
      preLoaderRoute: typeof GamesIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/$id/play': {
      id: '/games/$id/play'
      path: '/games/$id/play'
      fullPath: '/games/$id/play'
      preLoaderRoute: typeof GamesIdPlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/$id/edit': {
      id: '/games/$id/edit'
      path: '/games/$id/edit'
      fullPath: '/games/$id/edit'
      preLoaderRoute: typeof GamesIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthLinkRoute: AuthLinkRoute,
  GamesMineRoute: GamesMineRoute,
  GamesNewRoute: GamesNewRoute,
  GamesIdEditRoute: GamesIdEditRoute,
  GamesIdPlayRoute: GamesIdPlayRoute,
  GamesIdIndexRoute: GamesIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
