import { Hono } from "hono";
import { cors } from "hono/cors";
import { createAuth } from "@packages/db/auth";

// Types for CloudflareBindings should be generated by wrangler types
type Env = {
  DB: D1Database;
  IMAGES: R2Bucket;
  GOOGLE_CLIENT_ID?: string;
  GOOGLE_CLIENT_SECRET?: string;
  AUTH_BASE_URL?: string;
};

type Variables = {
  user: any | null;
  session: any | null;
};

const app = new Hono<{ Bindings: Env; Variables: Variables }>();

// CORS for auth endpoints
app.use(
  "/api/auth/*",
  cors({
    origin: ["http://localhost:3000", "https://loreland.pages.dev"],
    allowHeaders: ["Content-Type", "Authorization"],
    allowMethods: ["POST", "GET", "OPTIONS"],
    exposeHeaders: ["Content-Length"],
    maxAge: 600,
    credentials: true,
  })
);

// Auth middleware - get session for all routes
app.use("*", async (c, next) => {
  const auth = createAuth(c.env.DB, {
    baseURL: c.env.AUTH_BASE_URL,
    googleClientId: c.env.GOOGLE_CLIENT_ID,
    googleClientSecret: c.env.GOOGLE_CLIENT_SECRET,
  });

  const session = await auth.api.getSession({ headers: c.req.raw.headers });

  if (!session) {
    c.set("user", null);
    c.set("session", null);
    await next();
    return;
  }

  c.set("user", session.user);
  c.set("session", session.session);
  await next();
});

// Mount Better Auth handler
app.on(["POST", "GET"], "/api/auth/*", (c) => {
  const auth = createAuth(c.env.DB, {
    baseURL: c.env.AUTH_BASE_URL,
    googleClientId: c.env.GOOGLE_CLIENT_ID,
    googleClientSecret: c.env.GOOGLE_CLIENT_SECRET,
  });
  return auth.handler(c.req.raw);
});

// Health check
app.get("/health", (c) => {
  return c.json({ status: "ok", timestamp: new Date().toISOString() });
});

// Get current session
app.get("/api/session", (c) => {
  const user = c.get("user");
  const session = c.get("session");

  if (!user) {
    return c.json({ user: null, session: null });
  }

  return c.json({ user, session });
});

// Protected route example
app.get("/api/me", (c) => {
  const user = c.get("user");

  if (!user) {
    return c.json({ error: "Unauthorized" }, 401);
  }

  return c.json({ user });
});

export default app;
